[2017-05-14 09:04:38,576] {models.py:167} INFO - Filling up the DagBag from /Users/michaelkunc/Development/top_500_etl/airflow/dags/albums_write.py
[2017-05-14 09:04:39,143] {base_task_runner.py:112} INFO - Running: ['bash', '-c', 'airflow run albums write_local 2017-05-13T18:14:39.877572 --job_id 2 --raw -sd DAGS_FOLDER//Users/michaelkunc/Development/top_500_etl/albums_write.py']
[2017-05-14 09:04:39,561] {base_task_runner.py:95} INFO - Subtask: [2017-05-14 09:04:39,561] {__init__.py:57} INFO - Using executor SequentialExecutor
[2017-05-14 09:04:39,779] {base_task_runner.py:95} INFO - Subtask: [2017-05-14 09:04:39,778] {models.py:167} INFO - Filling up the DagBag from /Users/michaelkunc/Development/top_500_etl/airflow/dags/Users/michaelkunc/Development/top_500_etl/albums_write.py
[2017-05-14 09:04:40,085] {base_task_runner.py:95} INFO - Subtask: Traceback (most recent call last):
[2017-05-14 09:04:40,085] {base_task_runner.py:95} INFO - Subtask:   File "/Users/michaelkunc/.virtualenvs/top_500/bin/airflow", line 28, in <module>
[2017-05-14 09:04:40,085] {base_task_runner.py:95} INFO - Subtask:     args.func(args)
[2017-05-14 09:04:40,085] {base_task_runner.py:95} INFO - Subtask:   File "/Users/michaelkunc/.virtualenvs/top_500/lib/python3.5/site-packages/airflow/bin/cli.py", line 388, in run
[2017-05-14 09:04:40,085] {base_task_runner.py:95} INFO - Subtask:     dag = get_dag(args)
[2017-05-14 09:04:40,085] {base_task_runner.py:95} INFO - Subtask:   File "/Users/michaelkunc/.virtualenvs/top_500/lib/python3.5/site-packages/airflow/bin/cli.py", line 126, in get_dag
[2017-05-14 09:04:40,086] {base_task_runner.py:95} INFO - Subtask:     'parse.'.format(args.dag_id))
[2017-05-14 09:04:40,086] {base_task_runner.py:95} INFO - Subtask: airflow.exceptions.AirflowException: dag_id could not be found: albums. Either the dag did not exist or it failed to parse.
[2017-05-14 09:04:44,149] {jobs.py:2083} INFO - Task exited with return code 1
